[project]
name = "kpi-cee"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "pytest>=8.0.0",
    "pyinstaller>=6.0.0",
]
