from .balance_sheet_config import (
    BALANCE_SHEET_STRUCTURE,
    POSITION_NAMES,
    SECTION_TITLES
)
from .kpi_config import AVAILABLE_KPIS
from .mappings_config import (
    CEE_TO_AUTOMOTIVE_CODES,
    AVAILABLE_MAPPINGS
)
from .kpi_requirements_logic import (
    get_all_positions,
    ALL_POSITIONS,
    KPI_REQUIREMENTS,
    POS_CURRENT_ASSETS,
    POS_LIQUID_ASSETS,
    POS_CASH,
    POS_CURRENT_LIABILITIES,
    POS_TOTAL_LIABILITIES,
    POS_TOTAL_EQUITY,
    POS_TOTAL_ASSETS,
    POS_IMMOBILIZZAZIONI_IMMATERIALI,
    POS_IMMOBILIZZAZIONI_MATERIALI,
    POS_IMMOBILIZZAZIONI_FINANZIARIE,
    POS_IMMOBILIZZAZIONI_NETTE,
    POS_DEBITI_TRIBUTARI,
    POS_DEBITI_PREVIDENZIALI,
    POS_DEBITI_OLTRE_12_MESI,
    POS_ATTIVITA_FINANZIARIE_CORRENTI,
    POS_TOTAL_LIABILITIES_EXCL_TFR
)

# Exported for calculator.py (ensure all needed are here)
__all__ = [
    'BALANCE_SHEET_STRUCTURE', 'ALL_POSITIONS', 'KPI_REQUIREMENTS', 'AVAILABLE_KPIS',
    'POSITION_NAMES', 'SECTION_TITLES', 'CEE_TO_AUTOMOTIVE_CODES', 'AVAILABLE_MAPPINGS',
    'get_all_positions',
    # Main POS lists
    'POS_CURRENT_ASSETS', 'POS_LIQUID_ASSETS', 'POS_CASH',
    'POS_CURRENT_LIABILITIES', 'POS_TOTAL_LIABILITIES', 'POS_TOTAL_EQUITY',
    'POS_TOTAL_ASSETS',
    # Dynamically defined POS lists
    'POS_IMMOBILIZZAZIONI_IMMATERIALI', 'POS_IMMOBILIZZAZIONI_MATERIALI',
    'POS_IMMOBILIZZAZIONI_FINANZIARIE', 'POS_IMMOBILIZZAZIONI_NETTE',
    'POS_DEBITI_TRIBUTARI', 'POS_DEBITI_PREVIDENZIALI',
    'POS_DEBITI_OLTRE_12_MESI',
    'POS_ATTIVITA_FINANZIARIE_CORRENTI',
    'POS_TOTAL_LIABILITIES_EXCL_TFR'
]